language: cpp
sudo: required
dist: trusty
compiler:
  - clang
os:
  # - linux
  - osx
before_install:
  # - if [ $TRAVIS_OS_NAME == linux ]; then ./travis-ci/dependencies.sh; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install jsoncpp && brew install curl; fi
script:
  - ./compile.sh && ./main TRAVIS_CI;

# Disabled LINUX temporary in favor to speed.
# TODO: After adding proper unit tests, enabled it for OSX and maybe travis "matrix" to test under multiple
# compiler and OS versions

